export const finalLetter = [
  "you've just travelled through an entire year of us; one photograph, one memory, one moment at a time. as i watched this come together, i found myself smiling at my screen over and over again. sometimes i laughed because i remembered exactly what happened after the picture was taken. sometimes i just sat there quietly because i couldn't believe how quickly an entire year had passed. before i knew it, i wasn't just making a website anymore. i was reliving one of the happiest years of my life.",
  "when we first met, i never imagined that one day i'd be sitting here making something like this for you. i don't think either of us knew what the next twelve months would hold. there was no way of knowing how many conversations we'd have, how many sunrises we'd watch together, how many random drives we'd go on, how many meals we'd share, or how many ordinary days would quietly become some of my favourite memories. if someone had asked me back then what this year would look like, i don't think i could have answered them. but if they asked me now, i'd simply tell them to look through this website, because i've realized that no matter how many words i write, these little moments will always tell our story better than i ever could.",
  "somewhere along the way, you stopped becoming just another person in my life. without either of us planning it, you slowly became my accha, my safe space, my best friend, and somehow i became your little puppykutty, acchande ponnumole. i don't think either of us can point to the exact moment it happened, because it wasn't one big conversation or one extraordinary day. it happened quietly, through a thousand little moments. every walk, every bhajan, every drive, every hug, every conversation, every random inside joke, every time you looked after me without expecting anything in return. before i even realized it, i'd found something i never knew i was searching for; my dad, my home, and a place where i could simply be me. i don't think i'll ever truly be able to put into words what that has meant to me. some of the greatest gifts we receive in life are impossible to measure, because they quietly become part of who we are. finally being returned back to my accha (cause we know this isn't our first lifetime together) was one of those gifts, and i will unquestionably spend the rest of my life being grateful for it.",
  "thank you for making me feel safe in ways that are difficult to explain. thank you for always making me feel heard, even when i was talking about something completely random. thank you for listening to every overthought thought, every excitement, every worry, every dream, and every little story i wanted to tell you. thank you for celebrating my happiest moments with me and quietly standing beside me through the difficult ones. thank you for believing in me during moments when i wasn't entirely sure of myself. thank you for never making me feel like i had to earn your love or your time. you simply gave both so freely, and i don't think you even realize how much of a difference that has made in my life. you loved me through ordinary days just as much as the extraordinary ones, and i think that's one of the most beautiful things anyone has ever done for me.",
  "while putting this together, i realized just how quickly a year can pass. it feels like yesterday that we took our first metro selfie, and now here we are looking back at twelve months filled with memories that somehow became part of who we are. every month has its own little chapter. july feels different from august. august feels different from october. every page carries its own story, its own feeling, its own little piece of us. together, they became something i don't think either of us expected; a year that i'll always look back on with so much gratitude.",
  "i also realized that the memories i treasure most aren't necessarily the biggest ones. they're not the milestones or the days that everyone else would remember. they're the little moments that probably didn't seem important at the time. watching the sunrise together. wandering around dubai with absolutely nowhere to be. sitting on the beach in comfortable silence. sharing pizza after tennis. laughing over absolutely nothing. you tying my shoelaces. random selfies that took two seconds to capture but somehow now hold an entire story. the more i looked through these memories, the more i realized that none of those moments became special because of where we were. they became special because somewhere along the way, you quietly became my favourite person to experience life with.",
  "i don't know exactly what the future has planned for us. life has a funny way of surprising people. there will be new places, new adventures, new challenges, and probably a few unexpected twists along the way. but if this past year has taught me anything, it's that the moments i'll treasure most probably won't be the ones we spend months planning. they'll be the random evenings, the spontaneous drives, the quiet conversations, the sunsets, the cocooned moments, and all the ordinary days that we'll spend together.",
  "if one year has given us all of this, i honestly can't wait to see what the years ahead have in store. i can't wait for the memories that haven't happened yet, the photographs we haven't taken yet, the inside jokes we haven't created yet, and the stories we'll one day look back on just like we're looking back on this year now. somehow, i don't think this website is really the end of anything. i think it's simply the first volume of a story that's still being written.",
  "so thank you, accha. thank you for every conversation, every laugh, every hug, every sunrise, every drive, every bhel, every piece of advice, every word of encouragement, every shoelace you tied, every memory we've made together.",
  "if this little website has taught me anything while making it, it's that a year isn't measured in three hundred and sixty-five days. it's measured in walks that never felt long enough, conversations that somehow made hours disappear, hugs that made everything else feel smaller, and quality time with my favourite person in the cosmos. that's what this year has been to me. not just twelve months, but a collection of moments that i'll always carry with me.",
  "happy one year.",
  "thank you for giving me a year that i'll carry with me for the rest of my life. no matter how many years pass, no matter where life takes us, there will always be a part of me that looks back on this first year with the biggest smile. because this wasn't just the year i made all these memories...it was the year i found my accha.",
  "here's to every memory we've made, and to every beautiful one that's still waiting for us.",
  "i love you.",
  "forever your little ponnukutty. ❤️"
];
